### PR TITLE
Add support for verified web site

### PR DESCRIPTION
**Pull request by scouten-adobe**

### CODE REVIEW

**Comment by scouten-adobe** [comment]
Will close #177

**Comment by jessecarter111** [comment]
Would like to reference this: https://dhs-svip.github.io/requirements-for-decentralized-identity/TrustArchitecture/ as an alternative approach.

**Comment by scouten-adobe** [comment]
See also https://github.com/creator-assertions/identity-assertion/issues/177#issuecomment-2353364054:

> It would be useful to consider control of a web path and not just web domain (e.g., example.com/user_xyz). Many content signers live in such systems, e.g., academics (university.edu/researcher_name), professionals (company_name.com/employee_name), individual contributors (blog_platform.com/blogger_name).

**Comment by scouten-adobe** [comment]
Links from chat in discussion today (21 October 2024):

* [Wix: Adding Additional Meta Tags to Your Site's Pages](https://support.wix.com/en/article/adding-additional-meta-tags-to-your-sites-pages)
* [Digicert: Domain Control Validation (DCV) Methods](https://docs.digicert.com/en/certcentral/manage-certificates/dv-certificate-enrollment/domain-control-validation--dcv--methods.html)
* [CA/B Forum: Baseline Requirements for TLS Server Certification](https://cabforum.org/working-groups/server/baseline-requirements/documents/) – §3.2.2.4

**Comment by scouten-adobe** [comment]
Points to consider from discussion today (21 October 2024):

Points to consider:

* Validation should include a verification that the same random value that was initially specified remains present at the designated URL.
* Creator should be able to specify a path within a domain.
* Consider how BlueSky and Mastodon do domain verification.

**Review by christianpaquin — APPROVED** [review]
This is a simple solution that works for creators controlling either a domain (`example.com`) or a path under a domain (`example.com/users/christian`).

**Comment by timbray** [comment]
The Digicert doc is useful.  There's no need to support all that stuff though? The TXT record and /.well-known methods are widely enough used that most providers should have little trouble deploying them. I'd start with those two and wait for someone to credibly demonstrate an interesting use-case where that isn't enough.

**Pull request merged**
